# Generated by Django 3.1.7 on 2021-03-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_item',
            name='deadline',
        ),
    ]
